Task 3 EquityCalculator.Web/EquityCalculator.Web/Models/Entities/EquityStatus.cs
using Microsoft.EntityFrameworkCore;

namespace EquityCalculator.Web.Models.Entities
{
    public class EquityStatus
    {
        public Guid Id { get; set; }
        public float Balance { get; set; }
        public DateTime DueDate { get; set; }
        public int Term { get; set; }
        public float Amount { get; set; }
        public float Interest { get; set; }
        public float Insurance { get; set; }
        public float Total {  get; set; }
        //public float Interest => Balance * (float)0.05;
        //public float Insurance => Amount * (float)0.01;
        //public float Total => Amount + Interest + Insurance;
    }
}

Task 3 EquityCalculator.Web/EquityCalculator.Web/Models/Entities/UserInput.cs
namespace EquityCalculator.Web.Models.Entities
{
    public class UserInput
    {
        public float sellingPrice { get; set; }
        public DateTime dateTime { get; set; } = DateTime.Now;
        public int equityTerm { get; set; }

        public float monthlyAmount => sellingPrice / equityTerm;
        public DateTime startDate => dateTime.AddMonths(1);
    }
}

Task 3 EquityCalculator.Web/EquityCalculator.Web/Models/ErrorViewModel.cs
namespace EquityCalculator.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Task 3 EquityCalculator.Web/EquityCalculator.Web/Controllers/EquityController.cs
using EquityCalculator.Web.Data;
using EquityCalculator.Web.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EquityCalculator.Web.Controllers
{
    public class EquityController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public EquityController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult InitialRun()
        {
            foreach (var entity in dbContext.EquityStatuses)
            {
                dbContext.EquityStatuses.Remove(entity);
            }
            dbContext.SaveChangesAsync();

            return Add();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(UserInput userInput)
        {
            foreach (var entity in dbContext.EquityStatuses)
            {
                dbContext.EquityStatuses.Remove(entity);
            }
            await dbContext.SaveChangesAsync();

            var initValue = new UserInput()
            {
                sellingPrice = userInput.sellingPrice,
                dateTime = userInput.dateTime,
                equityTerm = userInput.equityTerm
            };

            for (int i = 1; i <= userInput.equityTerm; i++)
            {
                EquityStatus temp = new EquityStatus()
                {
                    Balance = (float)Math.Round(initValue.sellingPrice - (i * initValue.monthlyAmount),2),
                    DueDate = initValue.startDate.AddMonths(i - 1),
                    Term = i,
                    Amount = (float)Math.Round(initValue.monthlyAmount, 2),
                };
                temp.Interest = (float)Math.Round(temp.Balance * (float)0.05, 2);
                temp.Insurance = (float)Math.Round(temp.Amount * (float)0.01, 2);
                temp.Total = (float)Math.Round(temp.Amount + temp.Interest + temp.Insurance,2);

                await dbContext.EquityStatuses.AddAsync(temp);
                await dbContext.SaveChangesAsync();
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var test = await dbContext.EquityStatuses.ToListAsync();
            return View(test);
        }
    }
}

Task 3 EquityCalculator.Web/EquityCalculator.Web/Controllers/HomeController.cs
using EquityCalculator.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EquityCalculator.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Task 3 EquityCalculator.Web/EquityCalculator.Web/Views/Equity/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model EquityCalculator.Web.Models.Entities.UserInput

<div class="text-center">
    <h1 class="display-4">Equity Calculator</h1>
</div>

<form method="post">
    <div class="mt-3">
        <label class="form-label">Selling Price: </label>
        <input type="text" class="form-control" asp-for="sellingPrice" />
    </div>

    <div class="mt-3">
        <label class="form-label">Reservation Date: </label>
        <input type="date" class="form-control" asp-for="dateTime" />
    </div>

    <div class="mt-3">
        <label class="form-label">Terms: </label>
        <input type="text" class="form-control" asp-for="equityTerm" />
    </div>

    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Check</button>
    </div>
</form>

Task 3 EquityCalculator.Web/EquityCalculator.Web/Views/Equity/List.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model List<EquityCalculator.Web.Models.Entities.EquityStatus>

<div class="text-left">
    <h1 class="display-4">Statements</h1>
</div>

<table width="800" height="120">
    <thead>
        <tr>
            <th>Balance</th>
            <th>Due Date</th>
            <th>Term</th>
            <th>Amount</th>
            <th>Interest</th>
            <th>Insurance</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var statement in Model)
        {
           <tr>
               <td>@statement.Balance</td>
               <td>@statement.DueDate</td>
               <td>@statement.Term</td>
               <td>@statement.Amount</td>
               <td>@statement.Interest</td>
               <td>@statement.Insurance</td>
               <td>@statement.Total</td>
           </tr>
        }
    </tbody>
</table>

Task 3 EquityCalculator.Web/EquityCalculator.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Task 3 EquityCalculator.Web/EquityCalculator.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EquityCalculator.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EquityCalculator.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EquityCalculator.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Equity" asp-action="Add">Calculator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Equity" asp-action="List">Statements</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EquityCalculator.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>